---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/werf:${_HELM_VERSION}
      - --tag=gcr.io/$PROJECT_ID/werf:latest
      - --tag=eu.gcr.io/$PROJECT_ID/werf:${_HELM_VERSION}
      - --tag=eu.gcr.io/$PROJECT_ID/werf:latest
      - --build-arg
      - HELM_VERSION=v${_HELM_VERSION}
      - --build-arg
      - WERF_VERSION=v${_WERF_VERSION}
      - '.'
  # Sanity Check: make sure basic functionality works
  - name: 'gcr.io/$PROJECT_ID/werf:latest'
    args: ['version']
    env:
      - SKIP_CLUSTER_CONFIG=true

images:
  - 'gcr.io/$PROJECT_ID/werf:${_HELM_VERSION}'
  - 'gcr.io/$PROJECT_ID/werf:latest'
  - 'eu.gcr.io/$PROJECT_ID/werf:${_HELM_VERSION}'
  - 'eu.gcr.io/$PROJECT_ID/werf:latest'
tags: ['cloud-builders-community']
substitutions:
  _HELM_VERSION: 3.3.1
  _WERF_VERSION: 1.1.22+fix20
